In [47]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("default")
import plotly.express as px


In [48]:
tf.__version__

'2.3.1'

In [49]:
dataset = pd.read_csv('tmdb_5000_movies.csv')
dataset

budget  popularity  revenue  runtime  vote_count  vote_average  \
0           0    0.126738        0    100.0           0           0.0   
1           0    0.407030        0      0.0           0           0.0   
2           0    0.028756        0     88.0           0           0.0   
3           0    0.042346        0    200.0           0           0.0   
4     3500000    1.618138        0    100.0           0           0.0   
...       ...         ...      ...      ...         ...           ...   
4798        0    0.296981        0      0.0           2           9.5   
4799        0    0.356495        0     99.0           1          10.0   
4800        0    0.376662   565592     97.0           1          10.0   
4801        1    0.094105        0     90.0           2          10.0   
4802        0    0.092100        0      0.0           1          10.0   

      Threshold  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
4798          3  
4799          3  
4800          3  
4801          3  
4802          3  

[4803 rows x 7 columns]

In [50]:
dataset = dataset.dropna()

In [51]:
dataset.shape

(4801, 7)

In [52]:
dataset.columns

Index(['budget', 'popularity', 'revenue', 'runtime', 'vote_count',
       'vote_average', 'Threshold'],
      dtype='object')

In [53]:
df = dataset

In [54]:
df.head()

budget  popularity  revenue  runtime  vote_count  vote_average  Threshold
0        0    0.126738        0    100.0           0           0.0          0
1        0    0.407030        0      0.0           0           0.0          0
2        0    0.028756        0     88.0           0           0.0          0
3        0    0.042346        0    200.0           0           0.0          0
4  3500000    1.618138        0    100.0           0           0.0          0

In [55]:
df = pd.get_dummies(df, columns=['Threshold'])
df.head()

budget  popularity  revenue  runtime  vote_count  vote_average  \
0        0    0.126738        0    100.0           0           0.0   
1        0    0.407030        0      0.0           0           0.0   
2        0    0.028756        0     88.0           0           0.0   
3        0    0.042346        0    200.0           0           0.0   
4  3500000    1.618138        0    100.0           0           0.0   

   Threshold_0  Threshold_1  Threshold_2  Threshold_3  
0            1            0            0            0  
1            1            0            0            0  
2            1            0            0            0  
3            1            0            0            0  
4            1            0            0            0

In [56]:
X = df.iloc[:, :-4].values
y = df.iloc[:, 6:10].values

In [57]:
X

array([[0.00000e+00, 1.26738e-01, 0.00000e+00, 1.00000e+02, 0.00000e+00,
        0.00000e+00],
       [0.00000e+00, 4.07030e-01, 0.00000e+00, 0.00000e+00, 0.00000e+00,
        0.00000e+00],
       [0.00000e+00, 2.87560e-02, 0.00000e+00, 8.80000e+01, 0.00000e+00,
        0.00000e+00],
       ...,
       [0.00000e+00, 3.76662e-01, 5.65592e+05, 9.70000e+01, 1.00000e+00,
        1.00000e+01],
       [1.00000e+00, 9.41050e-02, 0.00000e+00, 9.00000e+01, 2.00000e+00,
        1.00000e+01],
       [0.00000e+00, 9.21000e-02, 0.00000e+00, 0.00000e+00, 1.00000e+00,
        1.00000e+01]])

In [58]:
y

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       ...,
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=uint8)

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [60]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [61]:
X_train

array([[-6.91328390e-01, -4.90749229e-01, -5.13991760e-01,
        -5.69782777e-01, -5.43228558e-01,  1.01190877e+00],
       [-7.11008780e-01, -4.34296632e-01, -5.14383159e-01,
        -7.01218451e-01, -5.15645086e-01, -5.03061214e-01],
       [-6.22447025e-01,  4.21314191e-01, -4.77498508e-01,
        -1.00790169e+00,  4.00807544e-02,  1.26440377e+00],
       ...,
       [ 1.50303510e+00, -1.88814383e-01,  3.62469548e-01,
        -2.28186935e-04, -3.26617172e-01, -1.66401217e-01],
       [-5.90466391e-01,  7.96431451e-01, -2.39714853e-01,
        -1.13933737e+00,  3.54045572e-01,  1.70258779e-01],
       [-9.59965923e-02,  9.65770750e-01, -9.72748759e-02,
        -5.69782777e-01,  8.96790955e-01,  2.54423779e-01]])

In [62]:
X_test

array([[ 2.53625557e+00,  8.08505885e-01,  3.17056333e+00,
         3.94078837e-01,  1.32190094e+00,  8.60937804e-02],
       [-7.11008780e-01, -6.17699856e-01, -5.14383159e-01,
        -2.28186935e-04, -5.52152623e-01, -9.23886209e-01],
       [ 4.57809604e+00,  2.04812281e+00,  4.16990064e+00,
         1.27031667e+00,  4.78119289e+00,  3.38588778e-01],
       ...,
       [ 1.01102535e+00,  4.19119486e-01,  7.04525461e-01,
         3.50266945e-01,  1.20397336e-01, -5.03061214e-01],
       [-2.18999030e-01,  1.91497503e-01, -1.94196730e-01,
        -3.94535211e-01, -4.75373343e-02, -8.22362179e-02],
       [-7.11008780e-01, -6.48144139e-01, -5.14383159e-01,
        -5.25970885e-01, -5.61076687e-01, -3.44883618e+00]])

In [63]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=4, activation='softmax'))

In [64]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
history = ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
120/120 [==============================] - 0s 2ms/step - loss: 0.5559 - accuracy: 0.3513
Epoch 2/50
120/120 [==============================] - 0s 2ms/step - loss: 0.4615 - accuracy: 0.5453
Epoch 3/50
120/120 [==============================] - 0s 2ms/step - loss: 0.3293 - accuracy: 0.8430: 0s - loss: 0.4109 - accura
Epoch 4/50
120/120 [==============================

In [65]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred = np.where(y_pred == 'False',0, y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),4), y_test.reshape(len(y_test),4)),1))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[0 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 0]
 [0 0 1 ... 0 1 0]
 ...
 [0 1 0 ... 1 0 0]
 [0 0 1 ... 0 1 0]
 [1 0 0 ... 0 0 0]]


C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9968782518210197

In [67]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        39
           1       1.00      1.00      1.00       321
           2       1.00      1.00      1.00       587
           3       1.00      0.93      0.96        14

   micro avg       1.00      1.00      1.00       961
   macro avg       1.00      0.97      0.99       961
weighted avg       1.00      1.00      1.00       961
 samples avg       1.00      1.00      1.00       961



# Custom

In [68]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=4, activation='softmax'))

In [69]:
import keras
class CustomOptimizer(keras.optimizers.Optimizer):
    def __init__(self, learning_rate, name="CustomOptimizer", **kwargs):
        """Call super().__init__() and use _set_hyper() to store hyperparameters"""
        super().__init__(name, **kwargs)
        self._set_hyper("learning_rate", kwargs.get("lr", learning_rate)) # Must needed to specify the learning rate 
        self._is_first = True
    
    def _create_slots(self, var_list):
        """For each model variable, create the optimizer variable associated with it.
        TensorFlow calls these optimizer variables "slots".
        For momentum optimization, we need one momentum slot per model variable.
        """
        for var in var_list:
            self.add_slot(var, "pv") #taking previous weight or bias
        for var in var_list:
            self.add_slot(var, "pg") #taking previous gradient


    @tf.function
    def _resource_apply_dense(self, grad, var):
        """Update the slots and perform one optimization step for one model variable
        """
        var_dtype = var.dtype.base_dtype
        lr_t = self._decayed_lr(var_dtype) # handle learning rate decay
        new_var_m = var - (grad - 0.001) * lr_t * 10      #adding learning rate into new variable
        pv_var = self.get_slot(var, "pv")  #taking previous weights and bias 
        pg_var = self.get_slot(var, "pg")  #taking previous gradients
        
        if self._is_first:
            self._is_first = False
            new_var = new_var_m
        else:
            cond = grad*pg_var >= 0
            print(cond)
            avg_weights = (pv_var + var)/2.0
            new_var = tf.where(cond, new_var_m, avg_weights)
        pv_var.assign(var)
        pg_var.assign(grad)
        var.assign(new_var)

    def _resource_apply_sparse(self, grad, var):      #exceptions handing
        raise NotImplementedError

    def get_config(self):
        base_config = super().get_config()
        return {
            **base_config,
            "learning_rate": self._serialize_hyperparameter("learning_rate"),
        }


    def _resource_apply_sparse(self, grad, var):   #exceptions handing
        raise NotImplementedError

    def get_config(self):
        base_config = super().get_config()
        return {
            **base_config,
            "learning_rate": self._serialize_hyperparameter("learning_rate"),
            "decay": self._serialize_hyperparameter("decay"),
            "momentum": self._serialize_hyperparameter("momentum"),
        }

In [70]:
ann.compile(optimizer = CustomOptimizer(learning_rate=0.001), loss = 'binary_crossentropy', metrics = ['accuracy'])
history = ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing t

In [71]:
fig = px.line(y=history.history['accuracy'])
fig.show()
fig = px.line(y=history.history['loss'])
fig.show()

In [72]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred = np.where(y_pred == 'False',0, y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),4), y_test.reshape(len(y_test),4)),1))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[0 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 0]
 [0 0 1 ... 0 1 0]
 ...
 [0 1 0 ... 1 0 0]
 [0 0 1 ... 0 1 0]
 [1 0 0 ... 0 0 0]]


C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



In [73]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_pred)

0.963579604578564

In [74]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.64      0.78        39
           1       0.95      0.99      0.97       321
           2       0.97      0.99      0.98       587
           3       0.00      0.00      0.00        14

   micro avg       0.97      0.96      0.96       961
   macro avg       0.73      0.66      0.68       961
weighted avg       0.95      0.96      0.96       961
 samples avg       0.96      0.96      0.96       961



C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.

