In [29]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("default")
import plotly.express as px


In [30]:
tf.__version__

'2.3.1'

In [31]:
dataset = pd.read_csv('Movieson.csv')
dataset

Netflix  Hulu  Prime Video  Disney+  Type  Runtime  IMDb  Threshold
0            0     1            0        0     0     60.0   0.0          0
1            0     0            1        0     0     60.0   0.0          0
2            0     0            1        0     0     55.0   0.0          0
3            0     0            1        0     0     42.0   0.0          0
4            0     0            1        0     0     65.0   1.0          0
...        ...   ...          ...      ...   ...      ...   ...        ...
16168        0     0            1        0     0     90.0   9.3          3
16169        0     0            1        0     0     83.0   9.3          3
16170        0     0            1        0     0     60.0   9.3          3
16171        0     0            1        0     0     68.0   9.3          3
16172        0     0            1        0     0    132.0   9.3          3

[16173 rows x 8 columns]

In [32]:
dataset = dataset.dropna()

In [33]:
dataset.shape

(15819, 8)

In [34]:
dataset.columns

Index(['Netflix', 'Hulu', 'Prime Video', 'Disney+', 'Type', 'Runtime', 'IMDb',
       'Threshold'],
      dtype='object')

In [35]:
df = dataset

In [36]:
df.head()

Netflix  Hulu  Prime Video  Disney+  Type  Runtime  IMDb  Threshold
0        0     1            0        0     0     60.0   0.0          0
1        0     0            1        0     0     60.0   0.0          0
2        0     0            1        0     0     55.0   0.0          0
3        0     0            1        0     0     42.0   0.0          0
4        0     0            1        0     0     65.0   1.0          0

In [37]:
df = pd.get_dummies(df, columns=['Threshold'])
df.head()

Netflix  Hulu  Prime Video  Disney+  Type  Runtime  IMDb  Threshold_0  \
0        0     1            0        0     0     60.0   0.0            1   
1        0     0            1        0     0     60.0   0.0            1   
2        0     0            1        0     0     55.0   0.0            1   
3        0     0            1        0     0     42.0   0.0            1   
4        0     0            1        0     0     65.0   1.0            1   

   Threshold_1  Threshold_2  Threshold_3  
0            0            0            0  
1            0            0            0  
2            0            0            0  
3            0            0            0  
4            0            0            0

In [38]:
X = df.iloc[:, :-4].values
y = df.iloc[:, 7:11].values

In [39]:
X

array([[  0. ,   1. ,   0. , ...,   0. ,  60. ,   0. ],
       [  0. ,   0. ,   1. , ...,   0. ,  60. ,   0. ],
       [  0. ,   0. ,   1. , ...,   0. ,  55. ,   0. ],
       ...,
       [  0. ,   0. ,   1. , ...,   0. ,  60. ,   9.3],
       [  0. ,   0. ,   1. , ...,   0. ,  68. ,   9.3],
       [  0. ,   0. ,   1. , ...,   0. , 132. ,   9.3]])

In [40]:
y

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       ...,
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=uint8)

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [42]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [43]:
X_train

array([[0.        , 0.        , 1.        , ..., 0.        , 0.09641434,
        0.70967742],
       [0.        , 0.        , 1.        , ..., 0.        , 0.09880478,
        0.75268817],
       [0.        , 0.        , 1.        , ..., 0.        , 0.08525896,
        0.70967742],
       ...,
       [1.        , 0.        , 0.        , ..., 0.        , 0.08286853,
        0.69892473],
       [1.        , 0.        , 0.        , ..., 0.        , 0.08605578,
        0.72043011],
       [0.        , 0.        , 1.        , ..., 0.        , 0.05976096,
        0.49462366]])

In [44]:
X_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.06055777,
        0.67741935],
       [0.        , 0.        , 1.        , ..., 0.        , 0.13466135,
        0.67741935],
       [0.        , 0.        , 1.        , ..., 0.        , 0.07968127,
        0.83870968],
       ...,
       [0.        , 0.        , 1.        , ..., 0.        , 0.07330677,
        0.75268817],
       [0.        , 0.        , 1.        , ..., 0.        , 0.09083665,
        0.75268817],
       [0.        , 0.        , 1.        , ..., 0.        , 0.03027888,
        0.87096774]])

In [45]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=4, activation='softmax'))

In [46]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
history = ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
396/396 [==============================] - 1s 2ms/step - loss: 0.5216 - accuracy: 0.3754
Epoch 2/50
396/396 [==============================] - 1s 2ms/step - loss: 0.3724 - accuracy: 0.6785: 0s - loss: 0.4398 - 
Epoch 3/50
396/396 [==============================] - 1s 2ms/step - loss: 0.1820 - accuracy: 0.9354: 0s - loss: 0.1833 - accuracy: 0.93
Epoch 4/50
396/396 [

In [47]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred = np.where(y_pred == 'False',0, y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),4), y_test.reshape(len(y_test),4)),1))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[0 0 1 ... 0 1 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9990518331226296

In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       302
           1       1.00      1.00      1.00      1144
           2       1.00      1.00      1.00       958
           3       1.00      1.00      1.00       760

   micro avg       1.00      1.00      1.00      3164
   macro avg       1.00      1.00      1.00      3164
weighted avg       1.00      1.00      1.00      3164
 samples avg       1.00      1.00      1.00      3164



# Custom

In [50]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=4, activation='softmax'))

In [51]:
import keras
class CustomOptimizer(keras.optimizers.Optimizer):
    def __init__(self, learning_rate, name="CustomOptimizer", **kwargs):
        """Call super().__init__() and use _set_hyper() to store hyperparameters"""
        super().__init__(name, **kwargs)
        self._set_hyper("learning_rate", kwargs.get("lr", learning_rate)) # Must needed to specify the learning rate 
        self._is_first = True
    
    def _create_slots(self, var_list):
        """For each model variable, create the optimizer variable associated with it.
        TensorFlow calls these optimizer variables "slots".
        For momentum optimization, we need one momentum slot per model variable.
        """
        for var in var_list:
            self.add_slot(var, "pv") #taking previous weight or bias
        for var in var_list:
            self.add_slot(var, "pg") #taking previous gradient


    @tf.function
    def _resource_apply_dense(self, grad, var):
        """Update the slots and perform one optimization step for one model variable
        """
        var_dtype = var.dtype.base_dtype
        lr_t = self._decayed_lr(var_dtype) # handle learning rate decay
        new_var_m = var - (grad - 0.001) * lr_t * 10      #adding learning rate into new variable
        pv_var = self.get_slot(var, "pv")  #taking previous weights and bias 
        pg_var = self.get_slot(var, "pg")  #taking previous gradients
        
        if self._is_first:
            self._is_first = False
            new_var = new_var_m
        else:
            cond = grad*pg_var >= 0
            print(cond)
            avg_weights = (pv_var + var)/2.0
            new_var = tf.where(cond, new_var_m, avg_weights)
        pv_var.assign(var)
        pg_var.assign(grad)
        var.assign(new_var)

    def _resource_apply_sparse(self, grad, var):      #exceptions handing
        raise NotImplementedError

    def get_config(self):
        base_config = super().get_config()
        return {
            **base_config,
            "learning_rate": self._serialize_hyperparameter("learning_rate"),
        }


    def _resource_apply_sparse(self, grad, var):   #exceptions handing
        raise NotImplementedError

    def get_config(self):
        base_config = super().get_config()
        return {
            **base_config,
            "learning_rate": self._serialize_hyperparameter("learning_rate"),
            "decay": self._serialize_hyperparameter("decay"),
            "momentum": self._serialize_hyperparameter("momentum"),
        }

In [52]:
ann.compile(optimizer = CustomOptimizer(learning_rate=0.001), loss = 'binary_crossentropy', metrics = ['accuracy'])
history = ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing t

In [53]:
fig = px.line(y=history.history['accuracy'])
fig.show()
fig = px.line(y=history.history['loss'])
fig.show()

In [54]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred = np.where(y_pred == 'False',0, y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),4), y_test.reshape(len(y_test),4)),1))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[0 0 1 ... 0 1 0]
 [0 0 1 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_pred)

0.9178255372945638

In [56]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.73      0.84       302
           1       0.93      0.92      0.93      1144
           2       0.92      0.92      0.92       958
           3       0.91      0.99      0.95       760

   micro avg       0.93      0.92      0.92      3164
   macro avg       0.94      0.89      0.91      3164
weighted avg       0.93      0.92      0.92      3164
 samples avg       0.92      0.92      0.92      3164



C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.

