In [30]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("default")
import plotly.express as px


In [31]:
tf.__version__

'2.3.1'

In [32]:
dataset = pd.read_csv('books.csv')
dataset

categories  num_pages  ratings_count  average_rating  \
0            Literary Criticism        176              0             0.0   
1                       Germany        128              0             0.0   
2     Biography & Autobiography        400              0             0.0   
3                         Games        112              0             0.0   
4                         Games        336              0             0.0   
...                         ...        ...            ...             ...   
6762        Juvenile Nonfiction         96              1             5.0   
6763                  Botanique         96              1             5.0   
6764           Health & Fitness         74              5             5.0   
6765  Biography & Autobiography        222              1             5.0   
6766             Spiritual life        304              1             5.0   

      Threshold  
0             0  
1             0  
2             0  
3             0  
4             0  
...         ...  
6762          2  
6763          2  
6764          2  
6765          2  
6766          2  

[6767 rows x 5 columns]

In [33]:
dataset = dataset.dropna()

In [34]:
dataset.shape

(6671, 5)

In [35]:
dataset.columns

Index(['categories', 'num_pages', 'ratings_count', 'average_rating',
       'Threshold'],
      dtype='object')

In [36]:
df = dataset

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['categories'] = le.fit_transform(df['categories'])

C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [38]:
df.head()

categories  num_pages  ratings_count  average_rating  Threshold
0         429        176              0             0.0          0
1         357        128              0             0.0          0
2         126        400              0             0.0          0
3         351        112              0             0.0          0
4         351        336              0             0.0          0

In [39]:
df = pd.get_dummies(df, columns=['Threshold'])
df.head()

categories  num_pages  ratings_count  average_rating  Threshold_0  \
0         429        176              0             0.0            1   
1         357        128              0             0.0            1   
2         126        400              0             0.0            1   
3         351        112              0             0.0            1   
4         351        336              0             0.0            1   

   Threshold_1  Threshold_2  
0            0            0  
1            0            0  
2            0            0  
3            0            0  
4            0            0

In [40]:
X = df.iloc[:, :-3].values
y = df.iloc[:, 4:7].values

In [41]:
X

array([[429., 176.,   0.,   0.],
       [357., 128.,   0.,   0.],
       [126., 400.,   0.,   0.],
       ...,
       [370.,  74.,   5.,   5.],
       [126., 222.,   1.,   5.],
       [536., 304.,   1.,   5.]])

In [42]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=uint8)

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
X_train

array([[ 1.30702503, -0.94005371, -0.15953851, -1.72525423],
       [ 1.30702503, -0.605347  , -0.15225913,  1.35660742],
       [ 0.94888378, -0.10964213, -0.11715781,  0.11141079],
       ...,
       [ 0.0054873 , -0.44858563, -0.15950612, -0.54231744],
       [-0.08186423, -0.78752913, -0.15849397, -0.16875845],
       [-2.94699426, -0.65195173, -0.15141703, -0.13762853]])

In [46]:
X_test

array([[ 1.34196564, -0.38079693, -0.14842916,  0.73400911],
       [ 0.79165103, -0.95276409, -0.15192715,  1.23208776],
       [ 0.0054873 , -0.41045449, -0.08324678, -0.82248668],
       ...,
       [-2.30059297,  0.64450717, -0.15781381,  0.67174928],
       [-1.06020131, -0.65195173, -0.10053428,  2.04146557],
       [ 0.0054873 , -0.24521953, -0.12186228, -0.4800576 ]])

In [47]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

In [48]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
history = ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
167/167 [==============================] - 0s 2ms/step - loss: 0.5528 - accuracy: 0.4734
Epoch 2/50
167/167 [==============================] - 0s 3ms/step - loss: 0.3483 - accuracy: 0.7961
Epoch 3/50
167/167 [==============================] - 1s 3ms/step - loss: 0.1756 - accuracy: 0.9442
Epoch 4/50
167/167 [==============================] - 1s 4ms/step - loss: 0.10

In [49]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred = np.where(y_pred == 'False',0, y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),3), y_test.reshape(len(y_test),3)),1))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 1 0 0 1 0]
 ...
 [0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 1 0 0 1 0]]


C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9992509363295881

In [51]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       1.00      1.00      1.00       741
           2       1.00      1.00      1.00       579

   micro avg       1.00      1.00      1.00      1335
   macro avg       1.00      0.98      0.99      1335
weighted avg       1.00      1.00      1.00      1335
 samples avg       1.00      1.00      1.00      1335



# Custom

In [52]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

In [53]:
import keras
class CustomOptimizer(keras.optimizers.Optimizer):
    def __init__(self, learning_rate, name="CustomOptimizer", **kwargs):
        """Call super().__init__() and use _set_hyper() to store hyperparameters"""
        super().__init__(name, **kwargs)
        self._set_hyper("learning_rate", kwargs.get("lr", learning_rate)) # Must needed to specify the learning rate 
        self._is_first = True
    
    def _create_slots(self, var_list):
        """For each model variable, create the optimizer variable associated with it.
        TensorFlow calls these optimizer variables "slots".
        For momentum optimization, we need one momentum slot per model variable.
        """
        for var in var_list:
            self.add_slot(var, "pv") #taking previous weight or bias
        for var in var_list:
            self.add_slot(var, "pg") #taking previous gradient


    @tf.function
    def _resource_apply_dense(self, grad, var):
        """Update the slots and perform one optimization step for one model variable
        """
        var_dtype = var.dtype.base_dtype
        lr_t = self._decayed_lr(var_dtype) # handle learning rate decay
        new_var_m = var - (grad - 0.001) * lr_t * 10      #adding learning rate into new variable
        pv_var = self.get_slot(var, "pv")  #taking previous weights and bias 
        pg_var = self.get_slot(var, "pg")  #taking previous gradients
        
        if self._is_first:
            self._is_first = False
            new_var = new_var_m
        else:
            cond = grad*pg_var >= 0
            print(cond)
            avg_weights = (pv_var + var)/2.0
            new_var = tf.where(cond, new_var_m, avg_weights)
        pv_var.assign(var)
        pg_var.assign(grad)
        var.assign(new_var)

    def _resource_apply_sparse(self, grad, var):      #exceptions handing
        raise NotImplementedError

    def get_config(self):
        base_config = super().get_config()
        return {
            **base_config,
            "learning_rate": self._serialize_hyperparameter("learning_rate"),
        }


    def _resource_apply_sparse(self, grad, var):   #exceptions handing
        raise NotImplementedError

    def get_config(self):
        base_config = super().get_config()
        return {
            **base_config,
            "learning_rate": self._serialize_hyperparameter("learning_rate"),
            "decay": self._serialize_hyperparameter("decay"),
            "momentum": self._serialize_hyperparameter("momentum"),
        }

In [54]:
ann.compile(optimizer = CustomOptimizer(learning_rate=0.001), loss = 'binary_crossentropy', metrics = ['accuracy'])
history = ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing t

In [55]:
fig = px.line(y=history.history['accuracy'])
fig.show()
fig = px.line(y=history.history['loss'])
fig.show()

In [56]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred = np.where(y_pred == 'False',0, y_pred)
print(np.concatenate((y_pred.reshape(len(y_pred),3), y_test.reshape(len(y_test),3)),1))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[[0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 1 0 0 1 0]
 ...
 [0 0 1 0 0 1]
 [0 0 1 0 0 1]
 [0 1 0 0 1 0]]


C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:

elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison



In [57]:
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_pred)

0.9835205992509364

In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.98      0.99      0.99       741
           2       0.99      1.00      0.99       579

   micro avg       0.98      0.98      0.98      1335
   macro avg       0.66      0.66      0.66      1335
weighted avg       0.97      0.98      0.98      1335
 samples avg       0.98      0.98      0.98      1335



C:\Users\KIIT\Anaconda3\envs\python 36 with tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

